### PR TITLE
fix: expand `full-border` plugin compatibility

### PR DESCRIPTION
**Pull request by lpnh**
Fixes https://github.com/yazi-rs/plugins/issues/3

### CODE REVIEW

**Comment by lpnh** [comment]
Now that I know they can be fixed, I will start working on a less hacky solution, particularly for the `max-preview` one.

**Comment by lpnh** [comment]
This is it. I don't think I can improve it further. Both issues have been addressed. Also, it should support cases when the `Parent` column is hidden, e.g:

```lua
ui.Layout()
	:direction(ui.Layout.HORIZONTAL)
	:constraints({
		ui.Constraint.Percentage(0),
		ui.Constraint.Percentage(30),
		ui.Constraint.Percentage(70),
	})
	:split(area)
```

That is the reason why I had to keep the following line:

```lua
x == 0 and ui.Bar.NONE or ui.Bar.TOP
```

I couldn't found a better way to handle it. For some reason I can't understand yet, the `Current` column render relies on this `ui.Bar`.

Anyway, there may be some use cases still missing, but overall, I think the `full-border` has become much more reliable.
Any feedback would be greatly appreciated. I'm open to addressing any requests for changes or clarifications. Also, feel free to take it from here.

**Comment by sxyazi** [comment]
Thanks for the patch!

I'll take a look later to see if there's a simpler way to implement it.

**Review by sxyazi — APPROVED** [review]
Thanks!

**Pull request merged**
